name: farmdashr
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.0+3

environment:
  sdk: ^3.10.3

dependencies:
  cloud_firestore: ^6.1.1
  dio: ^5.9.0
  equatable: ^2.0.7
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.3
  go_router: ^17.0.1
  google_sign_in: ^6.2.1
  image_picker: ^1.2.1
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.3.2
  cached_network_image: ^3.3.1
  http: ^1.6.0
  package_info_plus: ^9.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/sign_up/assets/

  fonts:
    - family: Arimo
      fonts:
        - asset: assets/fonts/Arimo-Regular.ttf
        - asset: assets/fonts/Arimo-Italic.ttf
          style: italic
        - asset: assets/fonts/Arimo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Arimo-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Arimo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Arimo-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Arimo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Arimo-BoldItalic.ttf
          weight: 700
          style: italic